#!/usr/bin/env bash

kde_device=Shiro

img=$(escrotum -s '/tmp/escrotum_%F_%T_$wx$h.png') &&\
    option=$(cat $HOME/.scripts/escrotum/options | sort | alacritty-fzf --info=hidden) &&\
    if [ "$option" == "clipboard" ]; then
        xclip -selection clipboard -t image/png < $img && rm $img
    elif [ "$option" == "save" ]; then
            mv $img ~/Pictures/prints
    elif [ "$option" == "imgur" ]; then
            id="48b71133055fc4a"
            response=$(https --ignore-stdin --check-status --form POST "api.imgur.com/3/upload" Authorization:"Client-ID $id" image@"$img") &&\
            echo $response | jq -r '.data.link' | xclip -selection clipboard && notify-send "Link sent to clipboard."
    elif [ "$option" == "phone" ]; then
            kdeconnect-cli -n $kde_device --share $img && sleep 8 && rm $img
    else
            exit
    fi
