#!/usr/bin/env bash

img=$(escrotum -s '/tmp/escrotum_%F_%T_$wx$h.png') &&\
    option=$(find $HOME/.scripts/escrotum/options/ -type f | cut -d '/' -f7 | sort | alacritty-fzf) &&\
    if [ "$option" == "clipboard" ]; then
        xclip -selection clipboard -t image/png < $img
    elif [ "$option" == "save" ]; then
            mv $img ~/Pictures/prints
    else 
            id="48b71133055fc4a"
            response=$(https --ignore-stdin --check-status --form POST "api.imgur.com/3/upload" Authorization:"Client-ID $id" image@"$img") &&\
            echo $response | jq -r '.data.link' | xclip -selection clipboard && notify-send "Link sent to clipboard."
    fi
