#!/usr/bin/env bash

if [ -n "$2" ]; then
    wanted="/$2"
else
    wanted=""
fi

id=$(https "api.jikan.moe/v3/search/anime?q=$1" | jq ".results[0].mal_id") &&\
    https api.jikan.moe/v3/anime/$id$wanted
