#!/usr/bin/env bash

i3lock --image=/home/rakki/Pictures/Wallpapers/aesthetic/among_trees___under_the_cliff_by_dadaws_de2faw8.jpg -B sigma -C --inside-color=292828 --ring-color=333131 --keyhl-color=b30452 --date-color=b30452 --time-color=3d138a --ind-pos="2900:700" --radius=50 --time-size=15 --date-size=10 --ring-width=7
