#!/usr/bin/env bash

i3lock -k --image=/home/rakki/Pictures/Wallpapers/aesthetic/among_trees___under_the_cliff_by_dadaws_de2faw8.jpg -B sigma -C --inside-color=00000000 --ring-color=3d138a --keyhl-color=b30452 --date-color=b30452 --time-color=3d138a
